jobs:
  - name: deploy-beanstalk-basic_runCI
    type: runCI
    flags:
      - deploy-eb-basic
    steps:
      - OUT: deploy-eb-basic-image

  - name: deploy-eb-basic-deploy
    type: runCLI
    flags:
      - deploy-eb-basic
    steps:
      - IN: deploy-eb-basic-image
      - IN: deploy-eb-basic-config
        switch: off
      - IN: deploy-eb-env-params
        switch: off
      - IN: deploy-eb-basic-repo
        switch: off
      - TASK:
        - script: cd $DEPLOYEBBASICREPO_STATE
        - script: shippable_replace single_container/Dockerrun.aws.json
        - script: cat single_container/Dockerrun.aws.json
        - script: BUCKET_NAME="shippable-deploy-eb"
        - script: BUCKET_KEY="$shippable-$JOB_ID-$BUILD_NUMBER"
        - script: echo \"BUCKET_NAME is: ${BUCKET_NAME}, and BUCKET_KEY is: ${BUCKET_KEY}.\"
        - script: tar -czvf $BUCKET_KEY.zip single_container/Dockerrun.aws.json
        - script: ls -al
        - script: aws s3 cp $BUCKET_KEY s3://$BUCKET_NAME/
        - script: aws elasticbeanstalk create-application-version --application-name ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_APPLICATION} --version-label $BUCKET_KEY --source-bundle S3Bucket=$BUCKET_NAME,S3Key=$BUCKET_KEY
        - script: aws elasticbeanstalk update-environment --application-name ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_APPLICATION} --environment-name ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_ENVIRONMENT_SINGLE} --version-label $BUCKET_KEY
        # - script: echo \"\" | eb init ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_APPLICATION} -r ${DEPLOYEBBASICCONFIG_POINTER_REGION}
        # - script: eb use ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_ENVIRONMENT_SINGLE}
        # - script: eb deploy ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_ENVIRONMENT_SINGLE}



  - name: deploy-eb-multi-deploy
    type: runCLI
    flags:
      - deploy-eb-basic
    steps:
      - IN: deploy-eb-basic-image
      - IN: deploy-eb-nginx-image
      - IN: deploy-eb-basic-config
        switch: off
      - IN: deploy-eb-env-params
        switch: off
      - IN: deploy-eb-basic-repo
        switch: off
      - TASK:
        - script: cd $DEPLOYEBBASICREPO_STATE/multi_container
        - script: shippable_replace Dockerrun.aws.json
        - script: cat Dockerrun.aws.json
        - script: echo \"\" | eb init ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_APPLICATION} -r ${DEPLOYEBBASICCONFIG_POINTER_REGION}
        - script: eb use ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_ENVIRONMENT_MULTI}
        - script: eb deploy ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_ENVIRONMENT_MULTI}
