jobs:
  - name: deploy-beanstalk-basic_runCI
    type: runCI
    flags:
      - deploy-eb-basic
    steps:
      - OUT: deploy-eb-basic-image

  - name: deploy-eb-basic-deploy
    type: runCLI
    flags:
      - deploy-eb-basic
    steps:
      - IN: deploy-eb-basic-image
      - IN: deploy-eb-basic-config
        switch: off
      - IN: deploy-eb-env-params
        switch: off
      - IN: deploy-eb-basic-repo
        switch: off
      - TASK:
        - script: aws elasticbeanstalk describe-applications
        - script: shippable_replace $DEPLOYEBBASICREPO_STATE/Dockerrun.aws.json
        - script: cat $DEPLOYEBBASICREPO_STATE/Dockerrun.aws.json
