branch-defaults:
  default:
    environment: ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_ENVIRONMENT_MULTI}
environment-defaults:
  ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_ENVIRONMENT_MULTI}:
    branch: null
    repository: null
global:
  application_name: ${DEPLOYEBENVPARAMS_PARAMS_AWS_EB_APPLICATION}
